### ISSUE TITLE
Problems with generating s3Keys on Windows

### ISSUE THREAD

**Issue by 4ndr345** [mazay/s3sync-service#29]
### Steps to reproduce:
1. create a test configuration `config.yaml`
2. in `config.yaml` set local_path to `C:\\Users\\TestUser\\S3`
3. in `config.yaml` set bucket_path to `/foo/bar/`
4. sync with AWS S3

### Expected behavior:
for a file `test.txt` the generated `s3Key` should be `foo/bar/test.txt`

### Observed behavior:
for a file `test.txt` the generated `s3Key` is `foo\\bar\\test.txt`

### Comments
The observed behavior results in creating one file `foo\bar\test.txt` and not 2 folder `foo` and `bar` and one file `test.txt` on S3.

If help is needed I can create an pull request with a possible fix. 
How could a possible fix would look like? Before returning the generated `s3Key` transform it with the  [`filepath.ToSlash`](https://golang.org/pkg/path/filepath/#ToSlash) function.

OS: Windows 10 Pro
Go version: go1.14 windows/amd64

**Comment by mazay** [comment]
Hi, thanks for the bug report! The `ToSlash` solution looks good, feel free to raise a PR if you have a spare minute. :)

**Comment by 4ndr345** [comment]
OK, will do

**Comment by mazay** [comment]
Hi @4ndr345 , the issue seems to be fixed. Grateful if you could validate the fix in [0.0.11a](https://github.com/mazay/s3sync-service/releases/tag/0.0.11a).
