### ISSUE TITLE
Problems using filewatch and relative local_path

### ISSUE THREAD

**Issue by 4ndr345** [mazay/s3sync-service#30]
### Steps to reproduce:
1. create a test configuration `config.yaml`
2. in `config.yaml` set local_path to `.\\S3`
4. start `s3sync-service`
5. create new file `test.txt` in `S3` folder. 

### Expected behavior:
The file `test.txt` will be synced with AWS S3

### Observed behavior:
The file `test.txt` is not synced with AWS S3

### Comments:
The problem is that [`filepath.Rel`](https://github.com/mazay/s3sync-service/blob/f220243773531b6b9627d2cecccc662281df3ead/s3sync.go#L36) returns an error. The reason is the following. The file watcher returns an absolute `filePath` for example `C:\\Users\\TestUser\\S3\\test.txt`. Computing the relative path from `C:\\Users\\TestUser\\S3\\test.txt` and `.\\S3` results in an error. The current workaround is to always use an absolute `local_path` in the configuration.

If help is needed I can create an pull request with a possible fix.

OS: Windows 10 Pro
Go version: go1.14 windows/amd64

**Comment by mazay** [comment]
Hello, thanks for reporting this bug! Unfortunately, the proposed workaround would break the `bucket_path` functionality thus we need to take a closer look into that.

**Comment by 4ndr345** [comment]
@mazay I don't see why it would break the bucket_path. But it maybe could break the initial sync. I will investigate the problem a bit more. And FYI I don't propose my workaround as a fix. It is only a temporary solution for me to get it working.

**Comment by mazay** [comment]
@4ndr345 I see now, I misunderstood you :)
I think the problem is quite similar to #29 and seems to be related to the `generateS3Key` and windows path specifics. I need to spin up win env for further debugging.

**Comment by mazay** [comment]
Hi @4ndr345, alter a closer look it turned out that relative `local_path` is known to lead to the sync issues and it doesn't seem to be a bug, the application was designed to use absolute path. I'll update the documentation accordingly.
