### ISSUE TITLE
Unable to find s3 bucket

### ISSUE THREAD

**Issue by JohanLeirnes** [mazay/s3sync-service#762]
**Describe the bug**
No matter what I configure the application is unable to find the s3 bucket with the error

2023/12/22 13:49:57,stdout,"{\"@timestamp\":\"2023-12-22T12:49:57Z\",\"app\":\"s3sync-service\",\"level\":\"fatal\",\"message\":\"******************************-bucket: failed to get page 1, not found, ResolveEndpointV2\",\"version\":\"latest\"}
2023/12/22 13:49:57,stdout,"{\"@timestamp\":\"2023-12-22T12:49:57Z\",\"app\":\"s3sync-service\",\"level\":\"info\",\"message\":\"all systems go\",\"version\":\"latest\"}
2023/12/22 13:49:57,stdout,"{\"@timestamp\":\"2023-12-22T12:49:57Z\",\"app\":\"s3sync-service\",\"level\":\"info\",\"message\":\"starting 5 checksum workers\",\"version\":\"latest\"}
2023/12/22 13:49:57,stdout,"{\"@timestamp\":\"2023-12-22T12:49:57Z\",\"app\":\"s3sync-service\",\"level\":\"info\",\"message\":\"starting 5 upload workers\",\"version\":\"latest\"}
2023/12/22 13:49:57,stdout,"{\"@timestamp\":\"2023-12-22T12:49:57Z\",\"app\":\"s3sync-service\",\"level\":\"info\",\"message\":\"starting up\",\"version\":\"latest\"}
2023/12/22 13:49:57,stdout,"{\"@timestamp\":\"2023-12-22T12:49:57Z\",\"app\":\"s3sync-service\",\"level\":\"info\",\"message\":\"starting prometheus exporter on port 9350 and path /metrics\",\"version\":\"latest\"}
2023/12/22 13:49:57,stdout,"{\"@timestamp\":\"2023-12-22T12:49:57Z\",\"app\":\"s3sync-service\",\"level\":\"info\",\"message\":\"starting http server on port 8090\",\"version\":\"latest\"}

**To Reproduce**
Steps to reproduce the behaviour:

Config:

upload_workers: 5
checksum_workers: 5
sites:
- name: 'QCL completed'
  local_path: '/backup/QCL completed'
  bucket: '******************************-bucket'
  bucket_path: '/QCLab-syn-nas-02_1/QCL completed/'
  access_key: ************************
  secret_access_key: *********************************************
  bucket_region: 'eu-north-1'
  s3_ops_retries: 10

**Expected behaviour**
s3sync to start

**Environment (please complete the following information):**
 - OS: Docker (synology)
 - Version latest

**Comment by JohanLeirnes** [comment]
The IAM user has these permissions:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": "s3:*",
			"Effect": "Allow",
			"Resource": [
				"arn:aws:s3:::******************************-bucket/*",
				"arn:aws:s3:::******************************-bucket"
			],
			"Sid": ""
		},
		{
			"Effect": "Allow",
			"Action": "s3:ListAllMyBuckets",
			"Resource": "*",
			"Condition": {}
		}
	]
}
```

**Comment by JohanLeirnes** [comment]
When trying with 

```
AWS_ACCESS_KEY_ID=********************** AWS_SECRET_ACCESS_KEY="************************************" aws s3 ls --region eu-north-1 ************************************-bucket/
```

**Comment by mazay** [comment]
hi @JohanLeirnes , thank you for reporting this. It is [a bug](https://github.com/aws/aws-sdk-go-v2/issues/2370) in the AWS SDK, I will try to release a hotfix later today.

**Comment by mazay** [comment]
@JohanLeirnes please give [0.4.5](https://github.com/mazay/s3sync-service/releases/tag/0.4.5) a try.

**Comment by JohanLeirnes** [comment]
Hi, I will try after my winter holiday! atm I am using 0.4.3 atm
